spring:
  datasource:
    url: jdbc:mariadb://database-1.cbjmqcjskomt.ap-northeast-2.rds.amazonaws.com:3306
    username: meotjh
    password: rlawlsgks12
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
  config:
    activate:
      on-profile: dev


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 81
